package com.example.buspassapplication.screens.Purchase

class Data {
    companion object {
        val x = listOf(
            " AS Rao Nagar",
            " Abids",
            " Afzalgunj",
            "Afzalgunj Bus Station",
            " Aliabad",
            " Allwyn Colony",
            " Alwal",
            " Amberpet",
            " Ameerpet",
            " Attapur",
            " BHEL",
            " Bahadurpura",
            " Banjara Hills",
            " Begumpet",
            " Bharat Nagar",
            " Bolarum",
            " Botanical Garden",
            " CBS",
            " Chaderghat",
            " Chanda Nagar",
            " Charminar",
            " Chikkadpally",
            " Dilsukhnagar",
            " ECIL X Road",
            " East Marredpally",
            " Erragadda",
            " Erramanzil",
            " Falaknuma",
            " Film Nagar",
            " Financial District",
            " Gachibowli",
            " Gandipet",
            " Gowliguda",
            " Gudimalkapur",
            " Habsiguda",
            " Hafeezpet",
            " Hayathnagar",
            " Himayatnagar",
            " Hitech City",
            " Hydernagar",
            " JNTU",
            " Jubilee Hills",
            " Jubilee Hills Check Post",
            "Jubilee Bus Station",
            " KPHB",
            " Kachiguda",
            " Kapra",
            " Khairatabad",
            " Kondapur",
            " Kothapet",
            " Koti",
            " Koti Bus Terminal",
            " Kukatpally",
            " LB Nagar",
            " Lakdi-ka-pul",
            " Langar Houz",
            " Langer House",
            " Lingampally",
            " MGBS",
            " Madhapur",
            " Malakpet",
            " Malkajgiri",
            " Masab Tank",
            " Medchal",
            " Mehdipatnam",
            " Mettuguda",
            " Miyapur",
            " Moosapet",
            " Mozamjahi Market",
            " Musheerabad",
            " Nagole",
            " Nampally",
            " Narayanguda",
            " Narsingi",
            " Nimboliadda",
            " Nizampet",
            " Osmania Medical College",
            " Panjagutta",
            " Parade Ground",
            " Paradise",
            "Patancheru",
            "Patancheru Bus Station",
            " Patny",
            " Punjagutta",
            " RTC X Road",
            " Raidurgam",
            " Rajendranagar",
            " Ramanthapur",
            " Rethi Bowli",
            " SR Nagar",
            " Sangeet",
            "Secunderabad Junction",
            " Serilingampally",
            " Shaikpet",
            " Shalibanda",
            " Shilparamam",
            " Siddiamber Bazar",
            " Sultan Bazar",
            " Tarnaka",
            " Toli Chowki",
            " Tolichowki",
            " Uppal",
            "Uppal Depot",
            " Vanasthalipuram",
            " Zoo Park",
        )
        val fromOptions: List<String> = x
        val toOptions: List<String> = x
    }
}
